name: Auto Merge PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_PAT }}
          merge-method: squash
          squash-commit-title: 'PR #{{number}} {{title}}'
          squash-commit-message: 'PR #{{number}} {{title}}'
